name: BasicKit
version: '1.0-SNAPSHOT'
main: org.chamchi.basicKit.Initialize
api-version: '1.20'

commands:
  기본템설정:
    description: 관리자가 기본템을 설정할 수 있는 명령어입니다.
    aliases:
      - /rlqhsxpatjfwjd

  기본템:
    description: 유저가 기본템을 받을 수 있는 명령어입니다.
    aliases:
      - /rlqhsxpa
